
BoxLayout:
    orientation: "vertical"

    MDTopAppBar:
        title: "Camera App"
        elevation: 4
        left_action_items: [["menu", lambda x: nav_drawer.set_state("open")]]

    MDNavigationLayout:
        ScreenManager:
            id: content_manager

            HomeScreen:
                name: "home"

            GalaryScreen:
                name: "galary"

            SettingsScreen:
                name: "settings"

            AboutScreen:
                name: "about"


        MDNavigationDrawer:
            id: nav_drawer
            color: 0, 1, 0, 1

            MDNavigationDrawerMenu:
                spacing: "10dp"

                MDNavigationDrawerHeader:
                    title: "Camera App"
                    text: "CG"

                MDFlatButton:
                    text: "Home"
                    size_hint_x: 1
                    size_hint_y: None
                    height: dp(50)
                    on_release:
                        content_manager.current = "home"
                        nav_drawer.set_state("close")

                MDFlatButton:
                    text: "Galary"
                    size_hint_x: 1
                    size_hint_y: None
                    height: dp(50)
                    on_release:
                        content_manager.current = "galary"
                        nav_drawer.set_state("close")

                MDFlatButton:
                    text: "Settings"
                    size_hint_x: 1
                    size_hint_y: None
                    on_release:
                        content_manager.current = "settings"
                        nav_drawer.set_state("close")

                MDFlatButton:
                    text: "About"
                    size_hint_x: 1
                    size_hint_y: None
                    on_release:
                        content_manager.current = "about"
                        nav_drawer.set_state("close")


<HomeScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: "20dp"
        spacing: "15dp"

        MDLabel:
            id: greeting
            text: "Welcome to my Camera App!"
            halign: "center"
            size_hint_y: None
            height: self.texture_size[1] + dp(20)


<GalaryScreen>:
    MDBoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(15)

        MDLabel:
            text: "Galary Screen"
            halign: "center"

<SettingsScreen>:
    MDBoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(15)

        MDLabel:
            text: "Settings Screen"
            halign: "center"

<AboutScreen>:
    MDBoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(15)

        MDLabel:
            text: "About Screen"
            halign: "center"