
MDScreen:

    MDBoxLayout:
        orientation: "vertical"
        padding: "30dp"
        spacing: "20dp"

        Widget:
            size_hint_y: .3

        MDLabel:
            id: greeting
            text: "Welcome!"
            halign: "center"
            font_style: "H6"
            adaptive_height: True

        MDRaisedButton:
            text: "Say Hello"
            pos_hint: {"center_x": .5}
            on_release: app.say_hello()

        Widget:
            size_hint_y: .4
